# Generated by Django 4.1.5 on 2023-01-18 12:57

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado_em"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado_em"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("cargo", models.CharField(max_length=100, verbose_name="Cargo")),
            ],
            options={"verbose_name": "Cargo", "verbose_name_plural": "Cargos",},
        ),
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado_em"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado_em"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("name", models.CharField(max_length=100, verbose_name="Serviço")),
                (
                    "description",
                    models.CharField(max_length=300, verbose_name="Descrição"),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("lni-cog", "engrenagem"),
                            ("lni-stats-up", "grágico"),
                            ("lni-users", "usuários"),
                            ("lni-layers", "design"),
                            ("lni-mobile", "mobile"),
                            ("lni-rocket", "foguete"),
                        ],
                        max_length=20,
                        verbose_name="Icone",
                    ),
                ),
            ],
            options={"verbose_name": "Serviço", "verbose_name_plural": "Serviços",},
        ),
        migrations.CreateModel(
            name="Equipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado_em"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado_em"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("nome", models.CharField(max_length=150, verbose_name="Nome")),
                (
                    "biografia",
                    models.CharField(max_length=300, verbose_name="Biografia"),
                ),
                (
                    "imagem_perfil",
                    stdimage.models.StdImageField(
                        force_min_size=False,
                        upload_to="equipe",
                        variations={
                            "thumb": {"crop": True, "height": 480, "width": 480}
                        },
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "social_facebook",
                    models.CharField(
                        default="#", max_length=100, verbose_name="facebook"
                    ),
                ),
                (
                    "social_instagram",
                    models.CharField(
                        default="#", max_length=100, verbose_name="instagram"
                    ),
                ),
                (
                    "social_twitter",
                    models.CharField(
                        default="#", max_length=100, verbose_name="twitter"
                    ),
                ),
                (
                    "social_whatsapp",
                    models.CharField(
                        default="#", max_length=100, verbose_name="whatsapp"
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.cargo",
                        verbose_name="Cargo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Funcionário",
                "verbose_name_plural": "Funcionários",
            },
        ),
    ]
