# Generated by Django 4.1.5 on 2023-01-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servico",
            name="description",
            field=models.TextField(max_length=300, verbose_name="Descrição"),
        ),
    ]
