# Generated by Django 4.1.5 on 2023-01-18 13:37

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_servico_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipe",
            name="biografia",
            field=models.TextField(max_length=300, verbose_name="Biografia"),
        ),
        migrations.AlterField(
            model_name="equipe",
            name="imagem_perfil",
            field=stdimage.models.StdImageField(
                force_min_size=False,
                upload_to="equipe/<function get_file_path at 0x000001EC98EF91B0>",
                variations={"thumb": {"crop": True, "height": 480, "width": 480}},
                verbose_name="Imagem",
            ),
        ),
        migrations.AlterField(
            model_name="servico",
            name="icon",
            field=models.CharField(
                choices=[
                    ("lni-cog", "engrenagem"),
                    ("lni-stats-up", "gráfico"),
                    ("lni-users", "usuários"),
                    ("lni-layers", "design"),
                    ("lni-mobile", "mobile"),
                    ("lni-rocket", "foguete"),
                ],
                max_length=20,
                verbose_name="Icone",
            ),
        ),
    ]
