# Generated by Django 4.1.5 on 2023-01-18 14:21

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_equipe_imagem_perfil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipe",
            name="imagem_perfil",
            field=stdimage.models.StdImageField(
                force_min_size=False,
                upload_to=core.models.get_file_path,
                variations={"thumb": {"crop": True, "height": 480, "width": 480}},
                verbose_name="Imagem",
            ),
        ),
    ]
