# Generated by Django 4.1.5 on 2023-01-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_equipe_imagem_perfil"),
    ]

    operations = [
        migrations.CreateModel(
            name="Funcionalidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado_em"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado_em"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("name", models.CharField(max_length=50, verbose_name="Nome")),
                (
                    "description",
                    models.TextField(max_length=150, verbose_name="Descrição"),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("fa-duotone fa-feather", "pena"),
                            ("fa-duotone fa-bug", "bug"),
                            ("fa-duotone fa-fish", "peixe"),
                            ("fa-duotone fa-earth-americas", "planeta"),
                            ("fa-duotone fa-handshake", "aperto de mãos"),
                            ("fa-duotone fa-users", "usuários"),
                            ("fa-duotone fa-thumbs-up", "curtir"),
                            ("fa-duotone fa-paper-plane", "avião de papel"),
                        ],
                        max_length=30,
                        verbose_name="Ícone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Funcionalidade",
                "verbose_name_plural": "Funcionalidades",
            },
        ),
    ]
