# Generated by Django 4.1.5 on 2023-01-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_funcionalidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionalidade",
            name="icon",
            field=models.CharField(
                choices=[
                    ("fa-regular fa-feather", "pena"),
                    ("fa-regular fa-bug", "bug"),
                    ("fa-regular fa-fish", "peixe"),
                    ("fa-regular fa-earth-americas", "planeta"),
                    ("fa-regular fa-handshake", "aperto de mãos"),
                    ("fa-regular fa-users", "usuários"),
                    ("fa-regular fa-thumbs-up", "curtir"),
                    ("fa-regular fa-paper-plane", "avião de papel"),
                ],
                max_length=30,
                verbose_name="Ícone",
            ),
        ),
    ]
